---
resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource

  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: latest

resources:
  - name: selfhydro-state
    type: git
    source:
      uri: https://github.com/selfhydro/selfhydro-state.git

  - name: version
    type: semver
    source:
      driver: gcs
      bucket: selfhydro-versions
      key: selfhydro-state-state
      json_key: |
        {
          "type": "service_account",
          "project_id": "selfhydro-197504",
          "private_key_id": "((gcs-service_account.private_key_id))",
          "private_key": "((gcs-service_account.private_key))",
          "client_email": "((gcs-service_account.client_email))",
          "client_id": "((gcs-service_account.client_id))",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/concourse-deployment%40selfhydro-197504.iam.gserviceaccount.com"
        }

  - name: terraform
    type: terraform
    source:
      backend_type: gcs
      vars:
        credentials: ((gcpServiceAccount.json))
      backend_config:
        bucket: selfhydro-infra-state
        prefix: selfhydro-state-to-dynamodb
        credentials: ((gcpServiceAccount.json))

  - name: gcs-artifact-bucket
    type: google-cloud-storage
    source:
      bucket: selfhydro-build-artifacts
      versioned_file: selfhydro-state-release.zip
      json_key: |
        {
          "type": "service_account",
          "project_id": "selfhydro-197504",
          "private_key_id": "((gcs-service_account.private_key_id))",
          "private_key": "((gcs-service_account.private_key))",
          "client_email": "((gcs-service_account.client_email))",
          "client_id": "((gcs-service_account.client_id))",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/concourse-deployment%40selfhydro-197504.iam.gserviceaccount.com"
        }


jobs:
  - name: test
    plan:
      - get: selfhydro-state
        trigger: true
      - task: unit-test
        file: selfhydro-state/state/.ci/unit-test.yml
  - name: build
    plan:
      - get: selfhydro-state
        trigger: true
        passed: [test]
      - get: version
        params: {bump: patch}
      - task: archive
        file: selfhydro-state/state/.ci/archive.yml
      - put: gcs-artifact-bucket
        params:
          file: release/selfhydro-state-release.zip
          acl: private
      - put: version
        params: {file: version/version}
  - name: terraform-apply
    plan:
      - get: selfhydro-state
        trigger: true
        passed: [build]
      - get: terraform
      - get: gcs-artifact-bucket
      - put: terraform
        params:
          terraform_source: selfhydro-state/state/infra
          env_name: prod
          vars:
            aws_access_key: ((aws_access.key))
            aws_secret_key: ((aws_secret.key))
            function-local-directory: "gcs-artifact-bucket/selfhydro-state-release.zip"
